# Generated by Django 5.0.3 on 2024-03-23 14:50

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_versement', models.DateTimeField(default=datetime.datetime(2024, 3, 23, 15, 50, 55, 460058), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(1900, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(1900, 1, 1, 23, 59))])),
                ('num_versement', models.IntegerField(default=0)),
                ('montant_versement', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('agriculteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agriculteurs.agriculteurs')),
            ],
        ),
    ]
