# Generated by Django 5.0.3 on 2024-03-23 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_heures', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('agriculteur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agriculteurs.agriculteurs')),
            ],
        ),
    ]
